INSERT INTO public."Categories"(
    "Id", "PersianName", "EnglishName", "ParentCategoryId", "ImageUrl", 
    "CategoryPersianDesc", "CategoryEnglishDesc", "IsShowInLanding", 
    "CreatedAt", "UpdatedAt", "DeletedAt", "IsDeleted", "IsActive", 
    "CreatedBy", "UpdatedBy", "DeletedBy"
) VALUES 
(
    1,
    'لوپ دندان‌پزشکی',
    'Dental Loupes',
    NULL,
    '/uploads/categories/dental-loupes.jpg',
    'انواع لوپ گالیله‌ای و پریزماتیک برای دندان‌پزشکان، با بزرگ‌نمایی‌های مختلف.',
    'Galilean and prismatic dental loupes in a range of magnifications.',
    true,
    '2026-01-10 08:01:00',
    '2026-01-10 08:01:00',
    NULL,
    false,
    true,
    1,
    1,
    NULL
),
(
    2,
    'هدلایت و نورپردازی',
    'Headlights & Lighting',
    NULL,
    '/uploads/categories/headlights.jpg',
    'هدلایت‌های LED برای نورپردازی دقیق میدان کار دهانی.',
    'LED headlights for precise illumination of the oral working field.',
    true,
    '2026-01-10 08:02:00',
    '2026-01-10 08:02:00',
    NULL,
    false,
    true,
    1,
    1,
    NULL
),
(
    3,
    'فریم و لنز',
    'Frames & Lenses',
    NULL,
    '/uploads/categories/frames-lenses.jpg',
    'فریم‌های سبک و لنزهای اپتیکی مخصوص لوپ دندان‌پزشکی.',
    'Lightweight frames and optical lenses made for dental loupes.',
    true,
    '2026-01-10 08:03:00',
    '2026-01-10 08:03:00',
    NULL,
    false,
    true,
    1,
    1,
    NULL
),
(
    4,
    'لوازم جانبی',
    'Accessories',
    NULL,
    '/uploads/categories/accessories.jpg',
    'کیف حمل، بند، کاور و سایر لوازم جانبی لوپ.',
    'Carry cases, straps, covers and other loupe accessories.',
    true,
    '2026-01-10 08:04:00',
    '2026-01-10 08:04:00',
    NULL,
    false,
    true,
    1,
    1,
    NULL
),
(
    5,
    'هدلایت بی‌سیم',
    'Wireless Headlights',
    2,
    '/uploads/categories/wireless-headlights.jpg',
    'هدلایت‌های بی‌سیم با باتری قابل شارژ و وزن کم.',
    'Wireless headlights with rechargeable batteries and low weight.',
    false,
    '2026-01-10 08:05:00',
    '2026-01-10 08:05:00',
    NULL,
    false,
    true,
    1,
    1,
    NULL
),
(
    6,
    'لنز جایگزین',
    'Replacement Lenses',
    3,
    '/uploads/categories/replacement-lenses.jpg',
    'لنزهای جایگزین با بزرگ‌نمایی ۲.۵ تا ۶ برابر.',
    'Replacement lenses from 2.5x to 6x magnification.',
    false,
    '2026-01-10 08:06:00',
    '2026-01-10 08:06:00',
    NULL,
    false,
    true,
    1,
    1,
    NULL
),
(
    7,
    'محافظ و ایمنی',
    'Protection & Safety',
    4,
    '/uploads/categories/protection.jpg',
    'فیس‌شیلد و محافظ‌های چشم سازگار با لوپ.',
    'Face shields and eye protection compatible with loupes.',
    false,
    '2026-01-10 08:07:00',
    '2026-01-10 08:07:00',
    NULL,
    false,
    true,
    1,
    1,
    NULL
),
(
    8,
    'ست‌های ویژه',
    'Bundles',
    NULL,
    '/uploads/categories/bundles.jpg',
    'ست‌های ترکیبی لوپ و هدلایت با قیمت مناسب‌تر.',
    'Combined loupe and headlight sets at better value.',
    true,
    '2026-01-10 08:08:00',
    '2026-01-10 08:08:00',
    NULL,
    false,
    true,
    1,
    1,
    NULL
),
(
    9,
    'نگهداری و تمیزکاری',
    'Care & Cleaning',
    NULL,
    '/uploads/categories/care-cleaning.jpg',
    'کیت‌های تمیزکاری و نگهداری لنز و فریم.',
    'Cleaning and care kits for lenses and frames.',
    false,
    '2026-01-10 08:09:00',
    '2026-01-10 08:09:00',
    NULL,
    false,
    true,
    1,
    1,
    NULL
),
(
    10,
    'باتری و شارژر',
    'Batteries & Chargers',
    2,
    '/uploads/categories/batteries.jpg',
    'باتری‌های رزرو و شارژرهای هدلایت.',
    'Spare batteries and chargers for headlights.',
    false,
    '2026-01-10 08:10:00',
    '2026-01-10 08:10:00',
    NULL,
    false,
    true,
    1,
    1,
    NULL
);
