INSERT INTO public."PaymentMethod"(
    "Id", "Title", "Code", "IsOnline", "ConfigJson", "IsActive", "DisplayOrder", 
    "CreatedAt", "UpdatedAt", "DeletedAt", "IsDeleted", "CreatedBy", "UpdatedBy", "DeletedBy"
) VALUES 
(
    1,
    'پرداخت آنلاین از طریق درگاه زرین‌پال',
    'Zarinpal',
    true,
    '{"MerchantID": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "Sandbox": false, "CallbackURL": "https://yourdomain.com/payment/callback"}',
    true,
    1,
    '2026-01-10 08:00:00',
    '2026-01-10 08:00:00',
    NULL,
    false,
    1,
    1,
    NULL
),
(
    2,
    'پرداخت آنلاین از طریق درگاه پِی‌پال',
    'PayPal',
    true,
    '{"ClientID": "xxxxxxxxxxxxxxxxxx", "Secret": "xxxxxxxxxxxxxxxxxx", "Sandbox": false, "Currency": "USD"}',
    true,
    2,
    '2026-01-10 08:05:00',
    '2026-01-10 08:05:00',
    NULL,
    false,
    1,
    1,
    NULL
),
(
    3,
    'پرداخت آنلاین از طریق درگاه زرین‌پال (تست)',
    'Zarinpal_Sandbox',
    true,
    '{"MerchantID": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "Sandbox": true, "CallbackURL": "https://yourdomain.com/payment/callback"}',
    false,
    3,
    '2026-01-10 08:10:00',
    '2026-01-10 08:10:00',
    NULL,
    false,
    1,
    1,
    NULL
),
(
    4,
    'پرداخت در محل (پس از تحویل)',
    'COD',
    false,
    '{"Description": "پرداخت نقدی هنگام تحویل سفارش"}',
    true,
    4,
    '2026-01-10 08:15:00',
    '2026-01-10 08:15:00',
    NULL,
    false,
    1,
    1,
    NULL
),
(
    5,
    'کارت به کارت (شبا)',
    'CardToCard',
    false,
    '{"BankName": "بانک ملی", "CardNumber": "6037-****-****-1234", "ShebaNumber": "IRXX-XXXXXXXXXXXX-XXXXXXXXXXXX"}',
    true,
    5,
    '2026-01-10 08:20:00',
    '2026-01-10 08:20:00',
    NULL,
    false,
    1,
    1,
    NULL
);